spring:
  application:
    name: cart-order-service-simple
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/ecomdb}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.block.ms: ${KAFKA_MAX_BLOCK_MS:500}
        request.timeout.ms: ${KAFKA_REQUEST_TIMEOUT_MS:500}
        delivery.timeout.ms: ${KAFKA_DELIVERY_TIMEOUT_MS:1000}
    admin:
      auto-create: true
      fail-fast: false

server:
  port: ${PORT:8080}

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

topics:
  cartItemAdded: ${CART_ITEM_ADDED_TOPIC:cart.item.added}

# toggle if you want to disable producing without changing code
kafka:
  enabled: ${KAFKA_ENABLED:true}
