name: CI/CD - Build & Push Docker Image

on:
  push:
    branches: [ "main" ]         # push to main -> build & push to Docker Hub
  pull_request:
    branches: [ "main" ]         # PRs -> build only (no push, no secrets)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/cart-order-service
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      # For PRs: build only (no push, no secrets)
      - name: Docker build (PR only)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: local/test:pr

      # For pushes to main: push to Docker Hub
      - name: Check Docker Hub secrets
        if: github.event_name == 'push'
        run: |
          test -n "${{ secrets.DOCKER_HUB_USERNAME }}" || { echo "Missing DOCKER_HUB_USERNAME"; exit 1; }
          test -n "${{ secrets.DOCKER_HUB_TOKEN }}" || { echo "Missing DOCKER_HUB_TOKEN"; exit 1; }

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Build & Push image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
